const { v4: uuidv4 } = require('uuid');

const mockLeads = [
  {
    id: '000200920191',
    createdAt: '2024-01-17T09:40:00Z',
    createdBy: 'Ramesh',
    createdByRole: 'Field Officer',
    source: 'Field Scouting',
    name: 'Radhika Devi',
    mobile: '9090990909',
    work: 'Home Maker',
    leadType: 'Individual',
    leadSource: 'Field Scouting',
    loanAmount: 25000,
    loanPurpose: 'Business',
    productType: 'Micro Loan',
    pincode: '560045',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    taluka: 'Bengaluru North',
    locality: 'Banaswadi',
    notes: 'Beside Maruthi Kirana Store',
    status: 'APPROVAL_PENDING',
    assignedTo: 'Gopal',
    office: 'Bengaluru North',
    center: 'Banaswadi C1',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'in_progress', completedAt: null, completedBy: null },
      { id: 's2', name: 'Qualification', status: 'pending', completedAt: null, completedBy: null },
      { id: 's3', name: 'Meet Lead', status: 'pending', completedAt: null, completedBy: null }
    ],
    callLogs: []
  },
  {
    id: '000200920192',
    createdAt: '2024-01-17T10:15:00Z',
    createdBy: 'Krishna',
    createdByRole: 'Back Office',
    source: 'Back Office',
    name: 'Suguna',
    mobile: '9876543210',
    work: 'Vegetable Vendor',
    leadType: 'Individual',
    leadSource: 'Back Office',
    loanAmount: 15000,
    loanPurpose: 'Working Capital',
    productType: 'Micro Loan',
    pincode: '500001',
    state: 'Andhra Pradesh',
    district: 'Renuka',
    taluka: 'Hyderabad',
    locality: 'Secunderabad',
    notes: '',
    status: 'QUALIFIED',
    assignedTo: 'Suresh',
    office: 'Hyderabad Central',
    center: 'Secunderabad C1',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'completed', completedAt: '2024-01-17T11:00:00Z', completedBy: 'Manoj' },
      { id: 's2', name: 'Qualification', status: 'completed', completedAt: '2024-01-17T12:00:00Z', completedBy: 'Arun' },
      { id: 's3', name: 'Meet Lead', status: 'in_progress', completedAt: null, completedBy: null }
    ],
    callLogs: [
      { id: 'cl1', calledAt: '2024-11-22T11:30:00Z', customerPickedUp: true, leadTemp: 'Hot', notes: 'Introduced and asked for relevant details', followUpAt: '2024-11-23T11:30:00Z' },
      { id: 'cl2', calledAt: '2024-11-23T14:00:00Z', customerPickedUp: false, leadTemp: 'Hot', notes: 'Left a voicemail regarding product details', followUpAt: '2024-11-24T14:00:00Z' }
    ]
  },
  {
    id: '000200920193',
    createdAt: '2024-01-17T11:30:00Z',
    createdBy: 'Amul',
    createdByRole: 'Field Officer',
    source: 'Inbound Call',
    name: 'Radhika Devi',
    mobile: '9123456789',
    work: 'Tailoring',
    leadType: 'Individual',
    leadSource: 'Inbound Call',
    loanAmount: 50000,
    loanPurpose: 'Business Expansion',
    productType: 'MSME Loan',
    pincode: '560001',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    taluka: 'Bengaluru South',
    locality: 'Jayanagar',
    notes: '',
    status: 'CONVERTED',
    assignedTo: 'Ravi',
    office: 'Bengaluru South',
    center: 'Jayanagar C2',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'completed', completedAt: '2024-01-17T12:00:00Z', completedBy: 'Ravi' },
      { id: 's2', name: 'Qualification', status: 'completed', completedAt: '2024-01-17T13:00:00Z', completedBy: 'Ravi' },
      { id: 's3', name: 'Meet Lead', status: 'completed', completedAt: '2024-01-17T15:00:00Z', completedBy: 'Ravi' }
    ],
    callLogs: []
  },
  {
    id: '000200920194',
    createdAt: '2024-01-18T08:50:00Z',
    createdBy: 'Sameer',
    createdByRole: 'Field Officer',
    source: 'Outbound Call',
    name: 'Vineeta Patel',
    mobile: '9988776655',
    work: 'Dairy Farming',
    leadType: 'Individual',
    leadSource: 'Outbound Call',
    loanAmount: 30000,
    loanPurpose: 'Asset Purchase',
    productType: 'Agri Loan',
    pincode: '580001',
    state: 'Karnataka',
    district: 'Dharwad',
    taluka: 'Dharwad',
    locality: 'Vidyanagar',
    notes: 'Interested in cattle loan',
    status: 'APPROVAL_PENDING',
    assignedTo: 'Suresh',
    office: 'Dharwad',
    center: 'Vidyanagar C1',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'in_progress', completedAt: null, completedBy: null },
      { id: 's2', name: 'Qualification', status: 'pending', completedAt: null, completedBy: null },
      { id: 's3', name: 'Meet Lead', status: 'pending', completedAt: null, completedBy: null }
    ],
    callLogs: []
  },
  {
    id: '000200920195',
    createdAt: '2024-01-19T03:20:00Z',
    createdBy: 'Jagan',
    createdByRole: 'Field Officer',
    source: 'Field Scouting',
    name: 'Pooja Verma',
    mobile: '9771234567',
    work: 'Petty Shop',
    leadType: 'Individual',
    leadSource: 'Field Scouting',
    loanAmount: 20000,
    loanPurpose: 'Working Capital',
    productType: 'Micro Loan',
    pincode: '522001',
    state: 'Andhra Pradesh',
    district: 'Guntur',
    taluka: 'Guntur',
    locality: 'Brodipet',
    notes: '',
    status: 'QUALIFIED',
    assignedTo: 'Mohan',
    office: 'Guntur',
    center: 'Brodipet C1',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'completed', completedAt: '2024-01-19T04:00:00Z', completedBy: 'Mohan' },
      { id: 's2', name: 'Qualification', status: 'in_progress', completedAt: null, completedBy: null },
      { id: 's3', name: 'Meet Lead', status: 'pending', completedAt: null, completedBy: null }
    ],
    callLogs: []
  },
  {
    id: '000200920197',
    createdAt: '2024-01-21T08:00:00Z',
    crmExternalId: 'CRM-2024-001',
    createdBy: 'CRM Integration',
    createdByRole: 'CRM',
    source: 'CRM',
    name: 'Meenakshi Sundaram',
    mobile: '9567890123',
    work: 'Garment Stitching',
    leadType: 'Individual',
    leadSource: 'CRM',
    loanAmount: 40000,
    loanPurpose: 'Business',
    productType: 'Micro Loan',
    pincode: '641001',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    taluka: 'Coimbatore North',
    locality: 'Gandhipuram',
    notes: 'Referred via partner CRM',
    status: 'APPROVAL_PENDING',
    assignedTo: 'Ravi Kumar',
    office: 'Coimbatore',
    center: 'Gandhipuram C1',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'in_progress', completedAt: null, completedBy: null },
      { id: 's2', name: 'Qualification', status: 'pending', completedAt: null, completedBy: null },
      { id: 's3', name: 'Meet Lead', status: 'pending', completedAt: null, completedBy: null }
    ],
    callLogs: []
  },
  {
    id: '000200920198',
    createdAt: '2024-01-22T10:30:00Z',
    crmExternalId: 'CRM-2024-002',
    createdBy: 'CRM Integration',
    createdByRole: 'CRM',
    source: 'CRM',
    name: 'Dharani Bai',
    mobile: '9412345678',
    work: 'Pickle Making',
    leadType: 'Individual',
    leadSource: 'CRM',
    loanAmount: 18000,
    loanPurpose: 'Working Capital',
    productType: 'Micro Loan',
    pincode: '462001',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    taluka: 'Bhopal',
    locality: 'Bagh Sewania',
    notes: 'CRM referral from partner bank',
    status: 'QUALIFIED',
    assignedTo: 'Gopal Nair',
    office: 'Bhopal Central',
    center: 'Bagh Sewania C1',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'completed', completedAt: '2024-01-22T12:00:00Z', completedBy: 'Gopal Nair' },
      { id: 's2', name: 'Qualification', status: 'completed', completedAt: '2024-01-23T10:00:00Z', completedBy: 'Gopal Nair' },
      { id: 's3', name: 'Meet Lead', status: 'in_progress', completedAt: null, completedBy: null }
    ],
    callLogs: []
  },
  {
    id: '000200920196',
    createdAt: '2024-01-20T09:05:00Z',
    createdBy: 'Janardhan',
    createdByRole: 'Field Officer',
    source: 'Inbound Call',
    name: 'Suguna Rao',
    mobile: '9845678901',
    work: 'Flower Vendor',
    leadType: 'Individual',
    leadSource: 'Inbound Call',
    loanAmount: 12000,
    loanPurpose: 'Business',
    productType: 'Micro Loan',
    pincode: '500003',
    state: 'Andhra Pradesh',
    district: 'Hyderabad',
    taluka: 'Secunderabad',
    locality: 'Trimulgherry',
    notes: '',
    status: 'REJECTED',
    assignedTo: 'Arun',
    office: 'Hyderabad East',
    center: 'Trimulgherry C1',
    rejectionReason: 'Low Credit Score',
    steps: [
      { id: 's1', name: 'Basic Details', status: 'completed', completedAt: '2024-01-20T10:00:00Z', completedBy: 'Arun' },
      { id: 's2', name: 'Qualification', status: 'completed', completedAt: '2024-01-20T11:00:00Z', completedBy: 'Arun' },
      { id: 's3', name: 'Meet Lead', status: 'pending', completedAt: null, completedBy: null }
    ],
    callLogs: []
  }
];

module.exports = { mockLeads };
